on:
  push:
    branches:
      - source  # default branch

jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2

      - run: somebuild

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          publish_branch: master  # deploying branch

# name: Jekyll Deploy

# on:
#   push:
#     branches:
#       - source

# jobs: 
#   build_and_deploy:
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v1
#       - name: Build & Deploy to GitHub Pages
#         env: 
#           GITHUB_TOKEN: ${{ secrets.JEKYLL_PAT}}
#           # GITHUB_REPOSITORY: ${{ secrets.GITHUB_REPOSITORY }}
#           # GITHUB_ACTOR: ${{ secrets.GITHUB_ACTOR }}
#         # uses: BryanSchuetz/jekyll-deploy-gh-pages@master
#         uses: helaili/jekyll-action@2.0.1
# name: Build and deploy Jekyll site to GitHub Pages

# on:
#   push:
#     branches:
#       - master

# jobs:
#   master:
#     runs-on: ubuntu-16.04
#     steps:
#       - uses: actions/checkout@v2
#       - uses: helaili/jekyll-action@2.0.1
#         env:
#           JEKYLL_PAT: ${{ secrets.JEKYLL_PAT }}


# on:
#   push:
#     branches:
#       - source  # default branch

# jobs:
#   deploy:
#     runs-on: ubuntu-18.04
#     steps:
#       - uses: actions/checkout@v2

#       - run: somebuild

#       - name: Deploy
#         uses: peaceiris/actions-gh-pages@v3
#         with:
#           github_token: ${{ secrets.JEKYLL_PAT }}
#           publish_dir: ./public
#           publish_branch: master  # deploying bran